[pytest]
DJANGO_SETTINGS_MODULE = strongswan_manager.settings.local
asyncio_mode = auto
addopts = --tb=short
filterwarnings =
    error
    ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning
    ignore::DeprecationWarning:APScheduler
    ignore::DeprecationWarning:channels
    ignore::pytest.PytestUnraisableExceptionWarning
