# Generated by Django 4.2.26

from django.db import migrations, models
import django.db.models.deletion
import strongMan.helper_apps.encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('auth', models.TextField()),
                ('round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField(unique=True)),
                ('auth', models.TextField()),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoCaAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.authentication')),
                ('ca_identity', models.TextField()),
            ],
            bases=('connections.authentication',),
        ),
        migrations.CreateModel(
            name='EapAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.authentication')),
                ('eap_id', models.TextField()),
            ],
            bases=('connections.authentication',),
        ),
        migrations.CreateModel(
            name='IKEv2Certificate',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.connection')),
            ],
            bases=('connections.connection',),
        ),
        migrations.CreateModel(
            name='IKEv2CertificateEAP',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.connection')),
            ],
            bases=('connections.connection',),
        ),
        migrations.CreateModel(
            name='IKEv2EAP',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.connection')),
            ],
            bases=('connections.connection',),
        ),
        migrations.CreateModel(
            name='IKEv2EapTls',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.connection')),
            ],
            bases=('connections.connection',),
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('data', strongMan.helper_apps.encryption.fields.EncryptedCharField(max_length=50)),
                ('authentication', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication', to='connections.authentication')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esp_proposals', to='connections.child')),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='connections.connection')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='connections.connection'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='connections.connection'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='remote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote', to='connections.connection'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('local_addresses', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_addresses', to='connections.connection')),
                ('local_ts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_ts', to='connections.child')),
                ('remote_addresses', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_addresses', to='connections.connection')),
                ('remote_ts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_ts', to='connections.child')),
                ('vips', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='connections.connection')),
            ],
        ),
        migrations.CreateModel(
            name='EapTlsAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.authentication')),
                ('eap_id', models.TextField()),
                ('identity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tls_identity', to='certificates.abstractidentity')),
            ],
            bases=('connections.authentication',),
        ),
        migrations.CreateModel(
            name='CertificateAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.authentication')),
                ('identity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cert_identity', to='certificates.abstractidentity')),
            ],
            bases=('connections.authentication',),
        ),
        migrations.CreateModel(
            name='CaCertificateAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='connections.authentication')),
                ('ca_identity', models.TextField()),
                ('ca_cert', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_cert_authentication', to='certificates.usercertificate')),
            ],
            bases=('connections.authentication',),
        ),
    ]
