# Generated by Django 4.2.26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('auth', models.CharField(max_length=56)),
                ('round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mode', models.TextField()),
                ('start_action', models.CharField(blank=True, choices=[('', 'none'), ('start', 'start'), ('trap', 'trap')], default=None, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField(unique=True)),
                ('version', models.CharField(choices=[('0', 'Any IKE version'), ('1', 'IKEv1'), ('2', 'IKEv2')], default=None, max_length=1)),
                ('send_certreq', models.BooleanField(blank=True, default=None, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('connection_type', models.TextField()),
                ('initiate', models.BooleanField(blank=True, default=None, null=True)),
                ('pool', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_pool', to='pools.pool')),
            ],
        ),
        migrations.CreateModel(
            name='AutoCaAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
                ('ca_identity', models.TextField()),
            ],
            bases=('server_connections.authentication',),
        ),
        migrations.CreateModel(
            name='EapCertificateAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
            ],
            bases=('server_connections.authentication',),
        ),
        migrations.CreateModel(
            name='IKEv2Certificate',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.connection')),
            ],
            bases=('server_connections.connection',),
        ),
        migrations.CreateModel(
            name='IKEv2CertificateEAP',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.connection')),
            ],
            bases=('server_connections.connection',),
        ),
        migrations.CreateModel(
            name='IKEv2EAP',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.connection')),
            ],
            bases=('server_connections.connection',),
        ),
        migrations.CreateModel(
            name='IKEv2EapTls',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.connection')),
            ],
            bases=('server_connections.connection',),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('child', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_esp_proposals', to='server_connections.child')),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_proposals', to='server_connections.connection')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_connections.connection')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_children', to='server_connections.connection'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_local', to='server_connections.connection'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='remote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_remote', to='server_connections.connection'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('local_addresses', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_local_addresses', to='server_connections.connection')),
                ('local_ts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_local_ts', to='server_connections.child')),
                ('remote_addresses', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_remote_addresses', to='server_connections.connection')),
                ('remote_ts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_remote_ts', to='server_connections.child')),
            ],
        ),
        migrations.CreateModel(
            name='EapTlsAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
                ('identity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_tls_identity', to='certificates.abstractidentity')),
            ],
            bases=('server_connections.authentication',),
        ),
        migrations.CreateModel(
            name='EapAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
                ('identity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_eap_identity', to='certificates.abstractidentity')),
            ],
            bases=('server_connections.authentication',),
        ),
        migrations.CreateModel(
            name='CertificateAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
                ('identity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_cert_identity', to='certificates.abstractidentity')),
            ],
            bases=('server_connections.authentication',),
        ),
        migrations.CreateModel(
            name='CaCertificateAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
                ('ca_identity', models.TextField()),
                ('ca_cert', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_ca_cert_authentication', to='certificates.usercertificate')),
            ],
            bases=('server_connections.authentication',),
        ),
    ]
