# Generated by Django 4.2.26

from django.db import migrations, models


def fix_eap_authentication(apps, schema_editor):
    # EapAuthentication previously acted like CertificateAuthentication and was stored as local auth round,
    # while an incorrect CaCertificateAuthentication was stored as remote auth with the selected EAP method
    # set as `auth` (instead of pubkey). we do keep a scheme like this for EAP-TLS authentication though,
    # where EapTlsAuthentication is used as local auth (with `auth` set to pubkey or eap-(t)tls for EAP-only)
    # and a CaCertificateAuthentication/AutoCaAuthentication as remote authentication with overridden auth
    # method that is stored on EapTlsAuthentication
    EapAuthentication = apps.get_model("server_connections", "EapAuthentication")
    CertificateAuthentication = apps.get_model("server_connections", "CertificateAuthentication")
    for eap in EapAuthentication.objects.all():
        conn = eap.local
        ca_auth = conn.server_remote.first()
        eap.auth = ca_auth.auth
        ca_auth.delete()
        eap.name = 'remote'
        eap.local = None
        eap.remote = conn
        eap.save()
        cert_auth = CertificateAuthentication(name='local', auth='pubkey', local=conn,
                                              identity=eap.identity)
        cert_auth.save()
    # for the combined certificate+EAP authentication a separate EapCertificateAuthentication was used as
    # second remote authentication round, which we can just replace with an EapAuthentication
    EapCertificateAuthentication = apps.get_model("server_connections", "EapCertificateAuthentication")
    for eap_cert in EapCertificateAuthentication.objects.all():
        conn = eap_cert.remote
        eap = EapAuthentication(name='remote-eap', auth=eap_cert.auth, remote=conn, round=eap_cert.round)
        eap_cert.delete()
        eap.save()


class Migration(migrations.Migration):

    dependencies = [
        ('server_connections', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_eap_authentication),
        migrations.RemoveField(
            model_name='eapauthentication',
            name='identity',
        ),
        migrations.AddField(
            model_name='eapauthentication',
            name='eap_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eaptlsauthentication',
            name='eap_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eaptlsauthentication',
            name='remote_auth',
            field=models.CharField(choices=[('eap-tls', 'eap-tls'), ('eap-ttls', 'eap-ttls')], default='0', max_length=56),
        ),
        migrations.DeleteModel(
            name='EapCertificateAuthentication',
        ),
    ]
