# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolname', models.TextField(unique=True)),
                ('addresses', models.TextField()),
                ('attribute', models.CharField(choices=[(None, 'None'), ('dns', 'dns'), ('nbns', 'nbns'), ('dhcp', 'dhcp'), ('netmask', 'netmask'), ('server', 'server'), ('subnet', 'subnet'), ('split_include', 'split_include'), ('split_exclude', 'split_exclude')], max_length=56, null=True)),
                ('attributevalues', models.TextField(null=True)),
            ],
        ),
    ]
