# Generated by Django 5.2.9 on 2026-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_unified_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='close_action',
            field=models.CharField(blank=True, choices=[('', 'none'), ('none', 'none'), ('clear', 'clear'), ('hold', 'hold'), ('restart', 'restart')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='dpd_action',
            field=models.CharField(blank=True, choices=[('', 'none'), ('none', 'none'), ('clear', 'clear'), ('hold', 'hold'), ('restart', 'restart')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='hw_offload',
            field=models.CharField(blank=True, choices=[('no', 'no'), ('yes', 'yes'), ('auto', 'auto'), ('packet', 'packet')], default='no', max_length=10),
        ),
    ]
