# Generated by Django 4.2.26

from django.db import migrations, models
import strongMan.helper_apps.encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('type', models.TextField()),
                ('password', strongMan.helper_apps.encryption.fields.EncryptedCharField(max_length=50)),
                ('salt', models.TextField()),
            ],
        ),
    ]
