name: CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Run unit tests
      run: ./runtests.py --no-cov --no-vici
    - name: Run flake8
      run: flake8 strongMan/

  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_PYTHON_VERSION: 3.13
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker images and start containers
      run: |
        docker compose build
        docker compose up -d
        sleep 5
    - name: Run unit tests, collect coverage
      run: docker compose exec -T roadwarrior /bin/sh -c "cd /strongMan; ./runtests.py"
    - name: Run integration tests
      run: docker compose exec -T roadwarrior /bin/sh -c "cd /strongMan; python manage.py test strongMan.tests.integration_tests --settings=strongMan.settings.local;"
    - name: Convert and copy coverage data
      run: docker compose exec -T roadwarrior /bin/sh -c "cd /strongMan; coverage xml -o -" > coverage.xml
    - name: Submit coverage
      uses: coverallsapp/github-action@v2
