# Generated by Django 4.2.26

from django.db import migrations, models
import django.db.models.deletion
import strongMan.apps.certificates.models.core
import strongMan.helper_apps.encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(strongMan.apps.certificates.models.core.DjangoAbstractBase, strongMan.apps.certificates.models.core.CertificateModel, models.Model),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('der_container', strongMan.helper_apps.encryption.fields.EncryptedField()),
                ('type', models.CharField(max_length=10)),
                ('algorithm', models.CharField(max_length=3)),
                ('public_key_hash', models.TextField()),
                ('serial_number', models.TextField()),
                ('hash_algorithm', models.CharField(max_length=20)),
                ('is_CA', models.BooleanField()),
                ('valid_not_after', models.DateTimeField()),
                ('valid_not_before', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=(strongMan.apps.certificates.models.core.CertificateModel, models.Model, strongMan.apps.certificates.models.core.DjangoAbstractBase),
        ),
        migrations.CreateModel(
            name='DistinguishedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('location', models.TextField()),
                ('country', models.TextField()),
                ('email', models.TextField()),
                ('organization', models.TextField()),
                ('unit', models.TextField()),
                ('cname', models.TextField()),
                ('province', models.TextField()),
            ],
            bases=(strongMan.apps.certificates.models.core.CertificateModel, models.Model),
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('der_container', strongMan.helper_apps.encryption.fields.EncryptedField()),
                ('type', models.CharField(max_length=10)),
                ('algorithm', models.CharField(max_length=3)),
                ('public_key_hash', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(strongMan.apps.certificates.models.core.CertificateModel, models.Model),
        ),
        migrations.CreateModel(
            name='DnIdentity',
            fields=[
                ('abstractidentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certificates.abstractidentity')),
            ],
            bases=('certificates.abstractidentity',),
        ),
        migrations.CreateModel(
            name='TextIdentity',
            fields=[
                ('abstractidentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certificates.abstractidentity')),
                ('text', models.TextField()),
            ],
            bases=('certificates.abstractidentity',),
        ),
        migrations.CreateModel(
            name='ViciCertificate',
            fields=[
                ('certificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certificates.certificate')),
                ('has_private_key', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('certificates.certificate',),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_issuer', to='certificates.distinguishedname'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_subject', to='certificates.distinguishedname'),
        ),
        migrations.AddField(
            model_name='abstractidentity',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ident_%(app_label)s_%(class)s', to='certificates.certificate'),
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('certificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certificates.certificate')),
                ('_nickname', models.TextField()),
                ('private_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.privatekey')),
            ],
            options={
                'abstract': False,
            },
            bases=('certificates.certificate',),
        ),
    ]
